version: '1'

services:

  clickhouse_db:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    volumes:
      - "clickhouse:/var/lib/clickhouse"
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: 123456
    ports:
      - "8123:8123"
      - "9000:9000"
volumes:
  clickhouse:
